import json
import os
import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "ci"))
sys.path.insert(0, str(ROOT / "githooks" / "lib"))

from heuristic import estimate_from_text
from parse_trailers import metric_from_raw, weighted_authorship


class EndToEndTests(unittest.TestCase):
    def test_fixture_commits_weight_to_ai_authored_mr(self):
        commits = json.loads((ROOT / "tests" / "fixtures" / "commits.json").read_text(encoding="utf-8"))
        metrics = [metric_from_raw(commit) for commit in commits]
        self.assertEqual(weighted_authorship(metrics), "ai-authored")

    def test_heuristic_reaches_target_accuracy_on_fixture_style_samples(self):
        samples = [
            ("generated by cursor agent\n" + "\n".join(f"+    def f_{i}(): return {i}" for i in range(240)), "ai-authored"),
            ("draft service with claude\n" + "\n".join(f"+const value{i} = {i};" for i in range(160)), "ai-authored"),
            ("refactor with ai assistance\n" + "\n".join(f"+value_{i} = {i}" for i in range(80)), "ai-assisted"),
            ("fix typo manually\n+typo = 'fixed'", "human"),
            ("update docs\n+Small note.", "human"),
        ]
        correct = sum(1 for text, expected in samples if estimate_from_text(text).authorship == expected)
        self.assertGreaterEqual(correct / len(samples), 0.7)

    def test_dashboard_and_sql_artifacts_exist(self):
        for path in [
            "sql/schema.sql",
            "sql/views.sql",
            "sql/queries/coverage.sql",
            "sql/queries/contribution.sql",
            "sql/queries/value.sql",
            "sql/queries/audit.sql",
            "dashboard/metabase/dashboards/coverage.json",
            "dashboard/metabase/dashboards/contribution.json",
            "dashboard/metabase/dashboards/value.json",
            "dashboard/metabase/dashboards/audit.json",
            "dashboard/metabase/import_dashboards.py",
        ]:
            self.assertTrue((ROOT / path).exists(), path)

    def test_git_hooks_run_in_fixture_repository(self):
        if not shutil.which("git"):
            self.skipTest("git is not available")
        with tempfile.TemporaryDirectory() as tmp:
            repo = Path(tmp)
            subprocess.run(["git", "init"], cwd=repo, check=True, stdout=subprocess.DEVNULL)
            subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=repo, check=True)
            subprocess.run(["git", "config", "user.name", "Test User"], cwd=repo, check=True)
            (repo / ".ai-coding-config.yml").write_text("authorship:\n  mode: manual\n", encoding="utf-8")

            hook_dir = repo / ".git" / "hooks"
            lib_dir = hook_dir / "ai-metrics-lib"
            lib_dir.mkdir(parents=True, exist_ok=True)
            for name in ("prepare-commit-msg", "commit-msg", "post-commit"):
                shutil.copy(ROOT / "githooks" / name, hook_dir / name)
                (hook_dir / name).chmod(0o755)
            for lib_file in (ROOT / "githooks" / "lib").iterdir():
                if lib_file.is_file():
                    shutil.copy(lib_file, lib_dir / lib_file.name)

            (repo / "sample.py").write_text("print('hello')\n", encoding="utf-8")
            subprocess.run(["git", "add", "sample.py"], cwd=repo, check=True)
            env = os.environ.copy()
            env["AI_METRICS_CHOICE"] = "ai-assisted"
            env["AI_METRICS_TOOL"] = "cursor"
            result = subprocess.run(
                ["git", "commit", "-m", "add sample"],
                cwd=repo,
                env=env,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
            )
            if result.returncode != 0:
                self.fail(result.stderr)
            message = subprocess.check_output(["git", "log", "-1", "--format=%B"], cwd=repo, text=True)
            self.assertIn("AI-Authorship: ai-assisted", message)
            self.assertIn("AI-Mode: manual", message)


if __name__ == "__main__":
    unittest.main()
