import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "githooks" / "lib"))

from heuristic import AUTHORSHIP_AI, AUTHORSHIP_ASSISTED, estimate_from_text


class HeuristicTests(unittest.TestCase):
    def test_detects_ai_authored_large_generated_commit(self):
        diff = "Generated by cursor agent\n" + "\n".join(
            f"+    def generated_func_{i}(): return {i}" for i in range(240)
        )
        estimate = estimate_from_text(diff)
        self.assertEqual(estimate.authorship, AUTHORSHIP_AI)
        self.assertLessEqual(estimate.human_edit_ratio, 30)

    def test_detects_assisted_medium_commit(self):
        diff = "Draft with ai assistance\n" + "\n".join(
            f"+value_{i} = {i}" for i in range(80)
        )
        estimate = estimate_from_text(diff)
        self.assertEqual(estimate.authorship, AUTHORSHIP_ASSISTED)


if __name__ == "__main__":
    unittest.main()
