from __future__ import annotations

import math
import re
from dataclasses import dataclass


@dataclass(frozen=True)
class StyleFeatures:
    line_count: int
    average_line_length: float
    line_length_stddev: float
    comment_ratio: float
    uniform_indent_ratio: float
    generated_phrase_ratio: float


GENERATED_PHRASES = (
    "generated by",
    "auto-generated",
    "this file was generated",
    "do not edit",
    "implementation plan",
)


def extract_added_lines(diff_text: str) -> list[str]:
    lines: list[str] = []
    for line in diff_text.splitlines():
        if line.startswith("+++") or line.startswith("---"):
            continue
        if line.startswith("+"):
            lines.append(line[1:])
    return lines


def _stddev(values: list[int], average: float) -> float:
    if not values:
        return 0.0
    variance = sum((v - average) ** 2 for v in values) / len(values)
    return math.sqrt(variance)


def features_from_lines(lines: list[str]) -> StyleFeatures:
    if not lines:
        return StyleFeatures(0, 0.0, 0.0, 0.0, 0.0, 0.0)

    lengths = [len(line) for line in lines]
    average = sum(lengths) / len(lengths)
    comment_lines = [
        line
        for line in lines
        if line.strip().startswith(("#", "//", "/*", "*", "--"))
    ]
    indented = [len(re.match(r"^\s*", line).group(0)) for line in lines if line.strip()]
    common_indents = sum(1 for n in indented if n % 2 == 0 or n % 4 == 0)
    generated_hits = sum(
        1
        for line in lines
        if any(phrase in line.lower() for phrase in GENERATED_PHRASES)
    )
    return StyleFeatures(
        line_count=len(lines),
        average_line_length=average,
        line_length_stddev=_stddev(lengths, average),
        comment_ratio=len(comment_lines) / len(lines),
        uniform_indent_ratio=common_indents / max(len(indented), 1),
        generated_phrase_ratio=generated_hits / len(lines),
    )


def ai_likelihood_from_features(features: StyleFeatures) -> float:
    if features.line_count == 0:
        return 0.0

    score = 0.0
    if features.line_count >= 80:
        score += 0.25
    elif features.line_count >= 30:
        score += 0.12

    if 45 <= features.average_line_length <= 110:
        score += 0.15
    if features.line_length_stddev < 35:
        score += 0.15
    if 0.05 <= features.comment_ratio <= 0.35:
        score += 0.15
    if features.uniform_indent_ratio >= 0.85:
        score += 0.15
    if features.generated_phrase_ratio > 0:
        score += 0.15

    return min(score, 1.0)


def score_diff(diff_text: str) -> float:
    return ai_likelihood_from_features(features_from_lines(extract_added_lines(diff_text)))
